### ISSUE TITLE
auto.offset.reset:latest not honored?

### ISSUE THREAD

**Issue by flolas** [wso2-extensions/siddhi-io-kafka#91] opened 2019-02-19 23:37 UTC
**Description:**
When setting optional
auto.offset.reset:latest
enable.auto.commit:false
parameters in kafka-consumer the expected behaviour is reading from the latest offset if the consumer group has not commited yet, but the behaviour is getting all messages from the beggining Using a new group id does not solve the problem.

**Affected Product Version:**
siddhi-io-kafka-4.1.13

**OS, DB, other environment details and versions:**
Centos, Kafka 0.10.0.1

**Comment by suhothayan** [comment] 2019-11-14 11:43
@pcnfernando can you check on this

**Comment by pcnfernando** [comment] 2019-11-14 14:57
To keep track of which messages that have already been processed, Siddhi-io-kafka source commits the offsets of the messages that were processed. This happens either by automatic means periodically (when **enable.auto.commit = true**) or manually in asynchronous manner (when **enable.auto.commit = false**).
In other words, with the current implementation, the offset will definitely will be committed.
This is the cause for **auto.offset.reset:latest** not behaving as expected.

In order to resolve this, we need to improve Siddhi-IO-Kafka extension to disable committing the offset if user configures. 
Will update the progress of this improvement in the issue.

**Closed as completed** 2019-11-28 06:42 UTC
